//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Self_Host_Web_API_REST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string JobTitle { get; set; }
        public long CompanyToken { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
